### ISSUE TITLE
Shouldn't this repo replace "workshop"?

### ISSUE THREAD

**Issue by NataliaLKB** [node-girls/cms-workshop#8]
Why the choice to make a new repo, rather then just replace the content of the existing one?

Or, why not call it "node-workshop" so that it is clear that we plan to reuse the content for subsequent workshops as well?

Just curious :)

**Comment by iteles** [comment]
Agreed, I would call it 'node-cms-workshop' for example (if that's still what we're planning on building) :+1:

**Comment by heron2014** [comment]
@NataliaLKB @iteles good shout. We will amend the name :+1:

**Comment by NataliaLKB** [comment]
This is done, will close.
